config/routes.rb
ClientPrj::Application.routes.draw do
  resources :petdetails

  resources :appointments

  resources :doctors

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
   attr_accessible :Customer, :DateOfVisit, :Doctor_id, :Pet, :Reason, :Reminder
   belongs_to :doctor
   has_many :petdetails
  
   validates :Customer, :presence =>true 
   validates :Pet, :presence =>true 
   validates :Reason, :presence =>true
  # validates_date_of :DateOfVisit, :before => DateTime.now.to_date
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :Address, :City, :CollegeName, :Experience, :Name, :State, :Zip, :appointments_attributes
   validates :Name, :length => {:maximum => 35, :minimum =>2}, :uniqueness =>true
   validates :Zip, :length => {:is => 5}
   validates_numericality_of :Experience, :greater_than => 1, :less_than => 100
   
   
    has_many :appointments
end

app/models/petdetail.rb
class Petdetail < ActiveRecord::Base
  attr_accessible :age, :appointment_id, :breed, :lastvisitdate, :nameofpet, :typeofpet, :weight
  belongs_to :appointment
  
  validates :NameofPet, :length => {:maximum => 35, :minimum =>2}, :presence =>true
  validates_inclusion_of :Breed, :in => %w( doc cat bird ), :message => "extension is not included in the list"
  validates :Age,:Weight,:LastVisitDate, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])
    @doctor = Doctor.find(@appointment.doctor_id)
    @doctorName = @doctor.Name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
   # @appointment = Appointment.new
   @doctor = Doctor.find(params[:id])
   @appointment = @doctor.appointments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
   #@appointment = Appointment.new(params[:appointment])

    @doctor = Doctor.find(params[:id])
    @appointment = @doctor.appointments.build(params[:appointment])
   
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors }
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.json
  def new
    
    @doctor = Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render json: @doctor, status: :created, location: @doctor }
      else
        format.html { render action: "new" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors/1
  # PUT /doctors/1.json
  def update
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      if @doctor.update_attributes(params[:doctor])
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/petdetails_controller.rb
class PetdetailsController < ApplicationController
  # GET /petdetails
  # GET /petdetails.json
  def index
    @petdetails = Petdetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @petdetails }
    end
  end

  # GET /petdetails/1
  # GET /petdetails/1.json
  def show
    @petdetail = Petdetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @petdetail }
    end
  end

  # GET /petdetails/new
  # GET /petdetails/new.json
  def new
     # @petdetail = Petdetail.new
    
     @appointment = Appointment.find(params[:id])
     @petdetail=  @appointment.petdetails.build
     

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @petdetail }
    end
  end

  # GET /petdetails/1/edit
  def edit
    @petdetail = Petdetail.find(params[:id])
  end

  # POST /petdetails
  # POST /petdetails.json
  def create
 # @petdetail = Petdetail.new(params[:petdetail])
    @appointment = Appointment.find(params[:id])
    @petdetail=  @appointment.petdetails.build(params[:petdetail])

    respond_to do |format|
      if @petdetail.save
        format.html { redirect_to @petdetail, notice: 'Petdetail was successfully created.' }
        format.json { render json: @petdetail, status: :created, location: @petdetail }
      else
        format.html { render action: "new" }
        format.json { render json: @petdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /petdetails/1
  # PUT /petdetails/1.json
  def update
    @petdetail = Petdetail.find(params[:id])

    respond_to do |format|
      if @petdetail.update_attributes(params[:petdetail])
        format.html { redirect_to @petdetail, notice: 'Petdetail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @petdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petdetails/1
  # DELETE /petdetails/1.json
  def destroy
    @petdetail = Petdetail.find(params[:id])
    @petdetail.destroy

    respond_to do |format|
      format.html { redirect_to petdetails_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/petdetails_helper.rb
module PetdetailsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
  <%= f.label "Date of Visit" %><br />
  <%= f.date_select :DateOfVisit %>
</div>
<div class="field">
  <%= f.label :Pet %><br />
  <%= f.text_field :Pet %>
</div>
<div class="field">
  <%= f.label :Customer %><br />
  <%= f.text_field :Customer %>
</div>
<div class="field">
  <%= f.label "Requires Reminder Of Appointment" %><br />
  <%= f.check_box :Reminder %>
</div>
<div class="field">
  <%= f.label "Reason for Visit" %><br />
  <%= f.text_area :Reason %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <tr>
    <th>Dateofvisit</th>
    <th>Pet</th>
    <th>Customer</th>
    <th>Reminder</th>
    <th>Reason</th>
    <th>Doctor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= link_to appointment.DateOfVisit ,:controller => "petdetails", :action => "new", :id => appointment %></td>
    <td><%= appointment.Pet %></td>
    <td><%= appointment.Customer %></td>
    <td><%= appointment.Reminder %></td>
    <td><%= appointment.Reason %></td>
    <td><%= link_to 'Show', appointment %></td>
    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
    <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'Goto Doctors', doctors_path %> | <%= link_to 'Goto Pet Details', petdetails_path %>

app/views/appointments/new.html.erb
<h1>New appointments</h1>

<%= form_for @appointment,:url => {:action => :create, :id => @doctor.id} do |f| %>
<% if @appointment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

    <ul>
    <% @appointment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label "Date of Visit" %><br />
  <%= f.date_select :DateOfVisit %>
</div>
<div class="field">
  <%= f.label :Pet %><br />
  <%= f.text_field :Pet %>
</div>
<div class="field">
  <%= f.label :Customer %><br />
  <%= f.text_field :Customer %>
</div>
<div class="field">
  <%= f.label "Requires Reminder Of Appointment" %><br />
  <%= f.check_box :Reminder %>
</div>
<div class="field">
  <%= f.label "Reason for Visit" %><br />
  <%= f.text_area :Reason %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<%end%>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date of Visit:</b>
  <%= @appointment.DateOfVisit %>
</p>

<p>
  <b>Pet:</b>
  <%= @appointment.Pet %>
</p>

<p>
  <b>Customer:</b>
  <%= @appointment.Customer %>
</p>

<p>
  <b>Requires Reminder of Appointment:</b>
  <%= @appointment.Reminder %>
</p>

<p>
  <b>Reason:</b>
  <%= @appointment.Reason %>
</p>
<p>
  <b>Doctor Name:</b>
  <%= @doctorName %>
</p>




<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Address %><br />
    <%= f.text_field :Address %>
  </div>
  <div class="field">
    <%= f.label :City %><br />
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br />
    <%= f.text_field :State %>
  </div>
  <div class="field">
    <%= f.label :Zip %><br />
    <%= f.text_field :Zip %>
  </div>
  <div class="field">
    <%= f.label :CollegeName %><br />
    <%= f.text_field :CollegeName %>
  </div>
  <div class="field">
    <%= f.label :Experience %><br />
    <%= f.number_field :Experience %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Collegename</th>
    <th>Experience</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= link_to doctor.Name,:controller => "appointments", :action => "new", :id => doctor %></td>
    <td><%= doctor.Address %></td>
    <td><%= doctor.City %></td>
    <td><%= doctor.State %></td>
    <td><%= doctor.Zip %></td>
    <td><%= doctor.CollegeName %></td>
    <td><%= doctor.Experience %></td>
    <td><%= link_to 'Show', doctor %></td>
    <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
    <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
	

<% end %>
</table>




<br />

<%= link_to 'New Doctor', new_doctor_path %> | <%= link_to 'Goto Appointements', appointments_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<tr>
		<td><b>Name:</b></td><td> <b>Address:</b></td><td><b>City:</b></td><td><b>State:</b></td><td> <b>Zip:</b></td><td><b>Collegename:</b></td><td><b>Experience:</b></td></tr>
<tr>				
<td>
  <%= @doctor.Name %>
</td>
<td>
  <%= @doctor.Address %>
</td>

<td>
  
  <%= @doctor.City %>
</td>

<td>
  
  <%= @doctor.State %>
</td>

<td>
 
  <%= @doctor.Zip %>
</td>

<td>
  
  <%= @doctor.CollegeName %>
</td>

<td>
  
  <%= @doctor.Experience %>
</td></tr></table>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

<h3>Appointments</h3>
<% for appointments in @doctor.appointments %>
	<%= appointments.Customer %> - <%= appointments.DateOfVisit %><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClientPrj</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/petdetails/_form.html.erb
<%= form_for(@petdetail) do |f| %>
  <% if @petdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@petdetail.errors.count, "error") %> prohibited this petdetail from being saved:</h2>

      <ul>
      <% @petdetail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Pet Name" %><br />
    <%= f.text_field :nameofpet %>
  </div>
  <div class="field">
    <%= f.label "Type of Pet" %><br />
    <%= f.text_field :typeofpet %>
  </div>
  <div class="field">
    <%= f.label "Breed" %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label "Age" %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label "Date of Last Visit" %><br />
    <%= f.date_select :lastvisitdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/petdetails/edit.html.erb
<h1>Editing petdetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @petdetail %> |
<%= link_to 'Back', petdetails_path %>

app/views/petdetails/index.html.erb
<h1>Listing petdetails</h1>

<table>
  <tr>
    <th>Nameofpet</th>
    <th>Typeofpet</th>
    <th>Breed</th>
    <th>Age</th>
    <th>Weight</th>
    <th>Lastvisitdate</th>
    <th>Appointment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @petdetails.each do |petdetail| %>
  <tr>
    <td><%= petdetail.nameofpet %></td>
    <td><%= petdetail.typeofpet %></td>
    <td><%= petdetail.breed %></td>
    <td><%= petdetail.age %></td>
    <td><%= petdetail.weight %></td>
    <td><%= petdetail.lastvisitdate %></td>
    <td><%= petdetail.appointment_id %></td>
    <td><%= link_to 'Show', petdetail %></td>
    <td><%= link_to 'Edit', edit_petdetail_path(petdetail) %></td>
    <td><%= link_to 'Destroy', petdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Goto Appointments', appointments_path %> | <%= link_to 'Goto Doctors', doctors_path %>

app/views/petdetails/new.html.erb
<h1>New petdetail</h1>
<%= form_for @petdetail,:url => {:action => :create, :id => @appointment.id} do |f| %>
  <% if @petdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@petdetail.errors.count, "error") %> prohibited this petdetail from being saved:</h2>

      <ul>
      <% @petdetail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Pet Name" %><br />
    <%= f.text_field :nameofpet %>
  </div>
  <div class="field">
    <%= f.label "Type of Pet" %><br />
    <%= f.text_field :typeofpet %>
  </div>
  <div class="field">
    <%= f.label "Breed" %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label "Age" %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label "Date of Last Visit" %><br />
    <%= f.date_select :lastvisitdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/petdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pet Name</b>
  <%= @petdetail.nameofpet %>
</p>

<p>
  <b>Type of Pet:</b>
  <%= @petdetail.typeofpet %>
</p>

<p>
  <b>Breed:</b>
  <%= @petdetail.breed %>
</p>

<p>
  <b>Age:</b>
  <%= @petdetail.age %>
</p>

<p>
  <b>Weight:</b>
  <%= @petdetail.weight %>
</p>

<p>
  <b>Date of Last Visit:</b>
  <%= @petdetail.lastvisitdate %>
</p>



<%= link_to 'Edit', edit_petdetail_path(@petdetail) %> |
<%= link_to 'Back', petdetails_path %>